
services: 

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks: 
      - node-network

  backend:
    depends_on:
        mongo:
          condition: service_started
    networks: 
      - node-network
    build: 
      context: backend
      dockerfile: Dockerfile
    container_name: backend
    working_dir: /usr/src/app
    env_file:
      - .env
    volumes: 
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    command: npm run dev

  frontend:
    depends_on:
      mongo:
        condition: service_started
    networks: 
      - node-network
    build: 
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend
    working_dir: /usr/src/app
    volumes: 
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3001"
    command: npm run start

volumes:
  mongo-data:
  
networks: 
  node-network:
    driver: bridge